global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#denis_lebedev'
