{
 "title": "Telegraf_Docker_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\"}",
     "legendFormat": "idle {{host}} ({{instance}})"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\"}",
     "legendFormat": "user {{host}} ({{instance}})"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "system {{host}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Mem available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mem_available_percent", "legendFormat": "{{host}} ({{instance}})" }
   ]
  },
  {
   "title": "Conatiner Mem usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage",
     "legendFormat": "{{container_name}} ({{container_status}})"
    }
   ]
  },
  {
   "title": "Docker CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}