- name: Add an apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
