plugin: gcp_compute
zones:
    - europe-north1-b
projects:
    - docker3-273507
service_account_file: /root/docker3-273507-fc2bf2a8ea9b.json
auth_kind: serviceaccount
keyed_groups: null
groups:
    dockerhost: '''docker-'' in name'
filters: 'status = RUNNING'
hostnames:
    - name
compose:
    ansible_host: 'networkInterfaces[0].accessConfigs[0].natIP'
    internal_ip: 'networkInterfaces[0].networkIP'
strict: true
